import Head from "next/head";
import styles from "./Layout.module.css"

const Layout = ({children}) =>{
    return(
        <div className={styles.container}>
            <Head>
            <title>Founders Lair</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>  
        {/* Headerzone */}
           Founders Lair
        </header>

        

      <main className={styles.main}>
        {children}
      </main>

      <footer className={styles.footer}>
        Project by Daniel Edison Essien
      </footer>
    </div>
    );
};

export default Layout;